#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
static id<MTLDevice> device;
static id<MTLCommandQueue> queue;
static id<MTLSamplerState> sampler;
static NSString* outDir;
static int W=640,H=360;
static void require(bool value,NSString* message){if(!value){fprintf(stderr,"%s\n",message.UTF8String);exit(1);}}
static id<MTLLibrary> library(NSString* path){NSError* error=nil;NSString* s=[NSString stringWithContentsOfFile:path encoding:NSUTF8StringEncoding error:&error];require(s!=nil,error.description);MTLCompileOptions* o=[MTLCompileOptions new];o.fastMathEnabled=NO;id<MTLLibrary> l=[device newLibraryWithSource:s options:o error:&error];require(l!=nil,error.description);return l;}
static id<MTLTexture> texture(MTLPixelFormat format=MTLPixelFormatRGBA8Unorm){MTLTextureDescriptor* d=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:format width:W height:H mipmapped:NO];d.usage=MTLTextureUsageShaderRead|MTLTextureUsageRenderTarget;d.storageMode=format==MTLPixelFormatDepth32Float_Stencil8?MTLStorageModePrivate:MTLStorageModeShared;return[device newTextureWithDescriptor:d];}
static id<MTLRenderPipelineState> pipeline(id<MTLLibrary> l,NSString* vs,NSString* fs,bool sdf=false,bool color=true,bool invert=false,bool glow=false){MTLRenderPipelineDescriptor*d=[MTLRenderPipelineDescriptor new];d.vertexFunction=[l newFunctionWithName:vs];d.fragmentFunction=[l newFunctionWithName:fs];d.colorAttachments[0].pixelFormat=MTLPixelFormatRGBA8Unorm;d.colorAttachments[0].writeMask=color?MTLColorWriteMaskAll:MTLColorWriteMaskNone;
 if(sdf){d.depthAttachmentPixelFormat=MTLPixelFormatDepth32Float_Stencil8;d.stencilAttachmentPixelFormat=MTLPixelFormatDepth32Float_Stencil8;}
 if(invert){auto a=d.colorAttachments[0];a.blendingEnabled=YES;a.sourceRGBBlendFactor=MTLBlendFactorOneMinusDestinationColor;a.destinationRGBBlendFactor=MTLBlendFactorZero;a.sourceAlphaBlendFactor=MTLBlendFactorOneMinusDestinationAlpha;a.destinationAlphaBlendFactor=MTLBlendFactorZero;}
 if(glow){MTLVertexDescriptor*v=[MTLVertexDescriptor vertexDescriptor];v.attributes[0].format=MTLVertexFormatFloat2;v.attributes[0].offset=0;v.attributes[0].bufferIndex=0;v.attributes[1].format=MTLVertexFormatFloat2;v.attributes[1].offset=8;v.attributes[1].bufferIndex=0;v.layouts[0].stride=16;d.vertexDescriptor=v;}
 NSError*e=nil;id<MTLRenderPipelineState>p=[device newRenderPipelineStateWithDescriptor:d error:&e];require(p!=nil,e.description);return p;}
static void save(id<MTLTexture> t,NSString*name){std::vector<unsigned char>b(W*H*4);[t getBytes:b.data() bytesPerRow:W*4 fromRegion:MTLRegionMake2D(0,0,W,H) mipmapLevel:0];require([[NSData dataWithBytes:b.data() length:b.size()] writeToFile:[outDir stringByAppendingPathComponent:name] atomically:YES],@"write failed");}
static void finish(id<MTLCommandBuffer>c){[c commit];[c waitUntilCompleted];require(c.status==MTLCommandBufferStatusCompleted,c.error.description);}
static void pass(id<MTLRenderPipelineState>p,id<MTLTexture>src,id<MTLTexture>dst,const void*u,size_t size,id<MTLTexture>aux=nil){static const float q[]={-1,1,0,0, 1,1,1,0, -1,-1,0,1, 1,1,1,0, 1,-1,1,1, -1,-1,0,1};auto c=[queue commandBuffer];auto d=[MTLRenderPassDescriptor renderPassDescriptor];d.colorAttachments[0].texture=dst;d.colorAttachments[0].loadAction=MTLLoadActionClear;d.colorAttachments[0].storeAction=MTLStoreActionStore;auto e=[c renderCommandEncoderWithDescriptor:d];[e setRenderPipelineState:p];[e setVertexBytes:q length:sizeof(q) atIndex:0];if(size)[e setFragmentBytes:u length:size atIndex:0];[e setFragmentTexture:src atIndex:0];[e setFragmentTexture:aux?:src atIndex:1];[e setFragmentSamplerState:sampler atIndex:0];[e setFragmentSamplerState:sampler atIndex:1];[e drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:6];[e endEncoding];finish(c);}
static id<MTLDepthStencilState> depth(bool distance,int winding,bool invert){auto d=[MTLDepthStencilDescriptor new];d.depthCompareFunction=distance?MTLCompareFunctionLessEqual:MTLCompareFunctionAlways;d.depthWriteEnabled=distance;auto s=[MTLStencilDescriptor new];s.stencilCompareFunction=invert?MTLCompareFunctionNotEqual:MTLCompareFunctionAlways;s.depthStencilPassOperation=invert?MTLStencilOperationZero:winding>0?MTLStencilOperationIncrementWrap:winding<0?MTLStencilOperationDecrementWrap:MTLStencilOperationKeep;s.stencilFailureOperation=invert?MTLStencilOperationZero:MTLStencilOperationKeep;s.depthFailureOperation=s.stencilFailureOperation;d.frontFaceStencil=s;d.backFaceStencil=s;return[device newDepthStencilStateWithDescriptor:d];}
int main(int argc,const char**argv){@autoreleasepool{require(argc==3,@"Usage: metal-reference shader-directory output-directory");NSString*shaders=@(argv[1]);outDir=@(argv[2]);device=MTLCreateSystemDefaultDevice();require(device!=nil,@"Metal device unavailable");queue=[device newCommandQueue];auto sd=[MTLSamplerDescriptor new];sd.minFilter=MTLSamplerMinMagFilterLinear;sd.magFilter=MTLSamplerMinMagFilterLinear;sd.sAddressMode=MTLSamplerAddressModeClampToEdge;sd.tAddressMode=MTLSamplerAddressModeClampToEdge;sampler=[device newSamplerStateWithDescriptor:sd];
 auto g=library([shaders stringByAppendingPathComponent:@"MetalGaussian.metal"]);auto glow=library([shaders stringByAppendingPathComponent:@"MetalQtTextSoftGlow.metal"]);auto s=library([shaders stringByAppendingPathComponent:@"MetalTextSdf.metal"]);
 auto input=texture();NSData*bytes=[NSData dataWithContentsOfFile:[outDir stringByAppendingPathComponent:@"input.rgba"]];require(bytes.length==W*H*4,@"bad RGBA fixture");[input replaceRegion:MTLRegionMake2D(0,0,W,H) mipmapLevel:0 withBytes:bytes.bytes bytesPerRow:W*4];auto t1=texture(),t2=texture(),t3=texture(),result=texture();
 struct Gaussian{float screen[4];int gammaEnabled;float gamma,count,sigma,dither,stepX,stepY;int border,alpha;};Gaussian gu={{640,360,1.0f/640,1.0f/360},0,2.2f,12,6.0f/W,0,1.0f/W,1.0f/H,0,1};
 pass(pipeline(g,@"qtTextGaussianVertex",@"qtTextGaussianXFragment"),input,t1,&gu,sizeof(gu));gu.sigma=6.0f/H;pass(pipeline(g,@"qtTextGaussianVertex",@"qtTextGaussianYFragment"),t1,result,&gu,sizeof(gu));save(result,@"gaussian.rgba");
 struct Threshold{int type;float low,high,smooth,gray;};Threshold threshold={0,.15f,1,1,0};
 pass(pipeline(glow,@"qtTextSoftGlowVertex",@"qtTextSoftGlowThresholdFragment",false,true,false,true),input,t1,&threshold,sizeof(threshold));
 float gx[]={12,6.0f/W,1.0f/W};float gy[]={12,6.0f/H,1.0f/H,1.5f};
 pass(pipeline(glow,@"qtTextSoftGlowVertex",@"qtTextSoftGlowXFragment",false,true,false,true),t1,t2,gx,sizeof(gx));
 pass(pipeline(glow,@"qtTextSoftGlowVertex",@"qtTextSoftGlowYFragment",false,true,false,true),t2,t3,gy,sizeof(gy));
 struct alignas(16) Blend{float exposure;unsigned pad[3];float color[3];unsigned pad2;int display;unsigned pad3[3];};Blend blend={1.5f,{0,0,0},{1,.65f,.3f},0,0,{0,0,0}};
 pass(pipeline(glow,@"qtTextSoftGlowVertex",@"qtTextSoftGlowBlendFragment",false,true,false,true),input,result,&blend,sizeof(blend),t3);save(result,@"soft-glow.rgba");
 NSData*dv=[NSData dataWithContentsOfFile:[outDir stringByAppendingPathComponent:@"distance.bin"]];NSData*sv=[NSData dataWithContentsOfFile:[outDir stringByAppendingPathComponent:@"shape.bin"]];require(dv.length>0&&sv.length>0,@"missing mesh");auto db=[device newBufferWithBytes:dv.bytes length:dv.length options:MTLResourceStorageModeShared];auto sb=[device newBufferWithBytes:sv.bytes length:sv.length options:MTLResourceStorageModeShared];auto depthTexture=texture(MTLPixelFormatDepth32Float_Stencil8);
 auto command=[queue commandBuffer];auto desc=[MTLRenderPassDescriptor renderPassDescriptor];desc.colorAttachments[0].texture=result;desc.colorAttachments[0].loadAction=MTLLoadActionClear;desc.colorAttachments[0].storeAction=MTLStoreActionStore;desc.depthAttachment.texture=depthTexture;desc.depthAttachment.clearDepth=1;desc.depthAttachment.loadAction=MTLLoadActionClear;desc.depthAttachment.storeAction=MTLStoreActionDontCare;desc.stencilAttachment.texture=depthTexture;desc.stencilAttachment.clearStencil=0;desc.stencilAttachment.loadAction=MTLLoadActionClear;desc.stencilAttachment.storeAction=MTLStoreActionDontCare;auto enc=[command renderCommandEncoderWithDescriptor:desc];[enc setFrontFacingWinding:MTLWindingCounterClockwise];[enc setStencilReferenceValue:0];
 [enc setRenderPipelineState:pipeline(s,@"textSdfMaterialDistanceVertex",@"textSdfDistanceFragment",true)];[enc setDepthStencilState:depth(true,0,false)];[enc setVertexBuffer:db offset:0 atIndex:0];[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:dv.length/32];
 auto shape=pipeline(s,@"textSdfMaterialShapeVertex",@"textSdfShapeFragment",true,false);[enc setRenderPipelineState:shape];[enc setVertexBuffer:sb offset:0 atIndex:0];[enc setDepthStencilState:depth(false,1,false)];[enc setCullMode:MTLCullModeBack];[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:sv.length/16];[enc setDepthStencilState:depth(false,-1,false)];[enc setCullMode:MTLCullModeFront];[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:sv.length/16];
 [enc setRenderPipelineState:pipeline(s,@"textSdfInverseVertex",@"textSdfInverseFragment",true,true,true)];[enc setDepthStencilState:depth(false,0,true)];[enc setCullMode:MTLCullModeNone];[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:6];[enc endEncoding];finish(command);save(result,@"sdf.rgba");
 NSDictionary*meta=@{@"device":device.name,@"width":@(W),@"height":@(H),@"shaderSource":@"Unmodified vendored Metal shaders",@"scope":@"Same WASM-generated mesh and same RGBA input; not whole desktop text pipeline parity"};NSData*json=[NSJSONSerialization dataWithJSONObject:meta options:NSJSONWritingPrettyPrinted error:nil];[json writeToFile:[outDir stringByAppendingPathComponent:@"reference.json"] atomically:YES];printf("%s\n",device.name.UTF8String);
}}
